stages:
  - test
  - build
  - publish

cache:
  untracked: true

test:
  stage: test
  script:
    - npm install
    - generate
    - npm run test --coverage
  tags:
    - NodeJS
    - NPM
    - Python 3.X

build:
  stage: build
  script:
    - generate
    - npm run production
    - npm run doc
    - cp doc dist/doc
  only:
    - tags
  tags:
    - NodeJS
    - NPM
    - Python 3.X
  artifacts:
    untracked: true
    paths:
      - ./dist

publish:
  stage: publish
  only:
    - tags
  script:
    - npm publish ./dist --access public
  tags:
    - NodeJS
    - NPM
  dependencies:
    - build
